### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by marcospassos**
Some bugs I found during preliminary testing.

### CODE REVIEW

**Comment by yar3333** [comment]
Thanks! I think, all good except next:
```
-public static function EMPTY() : ParserRuleContext { return self::$_EMPTY ?? (self::$_EMPTY = new ParserRuleContext()); }
+public static function createEmpty() : ParserRuleContext { return self::$_EMPTY ?? (self::$_EMPTY = new ParserRuleContext()); }
```

This is singleton creation (because PHP does not support `const EMPTY = new ....`). So, I think the name `createEmpty()` is not suitable. What your opinion?

**Comment by marcospassos** [comment]
Maybe `ParserRuleContext::emptyContext()`? I suggest a compound name in camel case because tokens names are in upper case and separated by underscores by convention, so the chances of conflicts are lower.

**Comment by marcospassos** [comment]
Btw, do you use any messaging app? Would make the communication faster.

**Comment by yar3333** [comment]
My skype: yar3333

**Review by yar3333 — APPROVED** [review]

**Pull request merged**
